In [73]:
import numpy as np
import scipy
from pprint import pprint
from numpy import array, zeros, diag, diagflat, dot
import time
from matplotlib import pyplot as plt

In [2]:
def bmatrix(a):
    """Returns a LaTeX bmatrix

    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{bmatrix}']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv +=  [r'\end{bmatrix}']
    return '\n'.join(rv)

In [13]:
#Define array

def symmetric_array_n(n):
    
    A = np.zeros((n, n))

    for i in range(0, n):
        for j in range(0, n):
            if i == j:
                A[i, j] = 2
            if np.abs(i-j) == 1:
                A[i, j] = -1

    return A

A = symmetric_array_n(10)
b = np.matrix([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).transpose()
X = np.linalg.lstsq(A, b)[0]

pprint(X)

matrix([[ 20.],
        [ 39.],
        [ 56.],
        [ 70.],
        [ 80.],
        [ 85.],
        [ 84.],
        [ 76.],
        [ 60.],
        [ 35.]])


In [114]:
def jacobi(A,b,N=25,x=None):
    start = time.time()
    """Solves the equation Ax=b via the Jacobi iterative method."""
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = zeros(len(A[0]))

    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    D = diag(A)
    R = A - diagflat(D)

    # Iterate for N times                                                                                                                                                                          
    for i in range(N):
        x = (b - dot(R,x)) / D
    
    stop = time.time()
    duration = stop - start
    return x, duration
    
guess = array([1.0,1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])

sol, duration = jacobi(A,b,N=1000,x=guess)

print "A:"
pprint(A)

print "b:"
pprint(b)

print "x:"
pprint(sol)

print "Duration: "
print duration, "s"

ValueError: shapes (9,9) and (10,) not aligned: 9 (dim 1) != 10 (dim 0)

In [102]:
#Gauss Siedel
ITERATION_LIMIT = 6000

x = np.zeros_like(b)
for it_count in range(ITERATION_LIMIT):
    x_new = np.zeros_like(x)

    for i in range(A.shape[0]):
        s1 = np.dot(A[i, :i], x_new[:i])
        s2 = np.dot(A[i, i + 1:], x[i + 1:])
        x_new[i] = (b[i] - s1 - s2) / A[i, i]

    if np.allclose(x, x_new, rtol=1e-8):
        break

    x = x_new

print("Solution:")
print(x)
error = np.dot(A, x) - b
#print("Error:")
#print(error)

Solution:
[[15]
 [30]
 [44]
 [56]
 [65]
 [70]
 [70]
 [64]
 [51]
 [30]]


In [80]:
eig = np.linalg.eig(A)[0]
print "Eigenvalues: "
pprint(eig)

Eigenvalues: 
array([ 3.91898595,  3.68250707,  3.30972147,  2.83083003,  2.28462968,
        1.71537032,  0.08101405,  0.31749293,  0.69027853,  1.16916997])


In [91]:
#Two Point Boundary Value Problem

x = np.arange(0, 1, .1)

def f(x):
    return -24*x**2

plt.plot(x, f(x))
plt.plot(0, 1, "bo")
plt.plot(1, 0, "bo")
plt.axes([0, 1, -100, 100])
plt.show()

In [106]:
#III Continuous into Discrete
N = 1000
delta_x = 1.0/(N+1.0)

x = np.zeros(N)
for i in range(0, N):
    x[i] = i*delta_x



In [117]:
# IVa.
A = symmetric_array_n(9)
b = x[:9]
guess = np.zeros_like(b)
sol, duration = jacobi(A, b, x=guess)

In [118]:
sol

array([ 0.00747109,  0.01536766,  0.02311619,  0.02998873,  0.0352573 ,
        0.0379329 ,  0.03702651,  0.03127427,  0.01941232])